siteTitle = 'Điểm Ăn Uống Bình Dương'
siteDescr = 'Địa điểm ăn uống Bình Dương'
siteDescription = "Hãy ăn uống ngay"
siteUrl = "http://diemanuongbinhduong.net"
siteBandcampUrl = 'http://diemanuongbinhduong.net'
siteMenuOne = 'Món Ngon'
siteMenuTwo = 'Quán Ăn'
siteMenuThree = 'Học Nấu Ăn'

siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/OdayakaPhuQuoc'
siteDiscogsUrl = 'https://www.discogs.com/label/82598-Sentimony-Records'
siteTwitterUrl = 'https://twitter.com/OdayakaPhuQuoc'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com'
siteYoutubeUrl = 'https://www.youtube.com/channel/UC2xhVmkOYPKibhJm3f0f3hw'

linkPrefix = '/'
